apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    app: cart
    tier: cart
    porject: roboshop

spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
      tier: cart
      porject: roboshop
  
  template:
    metadata:
      labels:
        app: cart
        tier: cart
        porject: roboshop
    
    spec:
      containers:
        - name: cart
          image: vasimphatan/cart:5.0.0
          envFrom:
          - configMapRef:
              name: cart


---
apiVersion: v1 
kind: Service
metadata:
  name: cart
  namespace: roboshop

spec:
  selector:
    app: cart
    tier: cart
    porject: roboshop
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP

---
apiVersion: v1 
kind: ConfigMap
metadata: 
  name: cart
  namespace: roboshop

data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: catalogue
  CATALOGUE_PORT: "8080"

    