apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop1
  labels:
    app: mongodb
    tier: mongodb
    project: roboshop1

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      tier: mongodb
      project: roboshop1
    
  template:
    metadata:
      labels:
        app: mongodb
        tier: mongodb
        project: roboshop1
    spec:
      containers:
      - name: mongodb
        image: vasimphatan/mongodb:6.0.0

---
apiVersion: v1 
kind: Service
metadata:
  name: mongodb
  namespace: roboshop1

spec:
  selector:
    app: mongodb
    tier: mongodb
    project: roboshop1
  ports:
  - protocol : TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP


  

        
