apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redis
  namespace: roboshop
  labels:
    app: redis
    tier: redis
    project: roboshop
  
spec:
    replicas: 1
    selector: 
      matchLabels:
        app: redis
        tier: redis
        project: roboshop
    template:
      metadata:
        labels:
          app: redis
          tier: redis
          project: roboshop

      spec:
        containers:
        - name: redis
          image: vasimphatan/redis:5.0.0

---
apiVersion: v1 
kind: Service
metadata:
  name: redis
  namespace: roboshop

spec:
  selector:
    app: redis
    tier: redis
    project: roboshop

  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP
